version: "3.4"

services:

  shrander-game:
    container_name: shrander-game
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/shrander-game
      - node_modules:/shrander-game/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "19007:19007"
    environment:
      NODE_ENV: development
      EXPO_USE_DEV_SERVER: 1
    entrypoint: "npm run start"

volumes:
  node_modules:
